const randomInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;

const countryData = {
  usa: {
    code: '1',
    areaCodes: [
      { code: '201', location: 'Jersey City, NJ' },
      { code: '202', location: 'Washington, DC' },
      { code: '203', location: 'New Haven, CT' },
      { code: '205', location: 'Birmingham, AL' },
      { code: '206', location: 'Seattle, WA' },
      { code: '207', location: 'Portland, ME' },
      { code: '208', location: 'Boise, ID' },
      { code: '209', location: 'Stockton, CA' },
      { code: '210', location: 'San Antonio, TX' },
      { code: '212', location: 'New York City, NY' },
      { code: '213', location: 'Los Angeles, CA' },
      { code: '214', location: 'Dallas, TX' },
      { code: '215', location: 'Philadelphia, PA' },
      { code: '216', location: 'Cleveland, OH' },
      { code: '217', location: 'Springfield, IL' },
      { code: '218', location: 'Duluth, MN' },
      { code: '219', location: 'Gary, IN' },
      { code: '224', location: 'Evanston, IL' },
      { code: '225', location: 'Baton Rouge, LA' },
      { code: '228', location: 'Gulfport, MS' },
      { code: '229', location: 'Albany, GA' },
      { code: '231', location: 'Muskegon, MI' },
      { code: '234', location: 'Akron, OH' },
      { code: '239', location: 'Fort Myers, FL' },
      { code: '240', location: 'Frederick, MD' },
      { code: '248', location: 'Troy, MI' },
      { code: '251', location: 'Mobile, AL' },
      { code: '252', location: 'Greenville, NC' },
      { code: '253', location: 'Tacoma, WA' },
      { code: '254', location: 'Waco, TX' },
      { code: '256', location: 'Huntsville, AL' },
      { code: '260', location: 'Fort Wayne, IN' },
      { code: '262', location: 'Kenosha, WI' },
      { code: '267', location: 'Philadelphia, PA' },
      { code: '269', location: 'Kalamazoo, MI' },
      { code: '270', location: 'Bowling Green, KY' },
      { code: '276', location: 'Bristol, VA' },
      { code: '281', location: 'Houston, TX' },
      { code: '301', location: 'Bethesda, MD' },
      { code: '302', location: 'Wilmington, DE' },
      { code: '303', location: 'Denver, CO' },
      { code: '304', location: 'Charleston, WV' },
      { code: '305', location: 'Miami, FL' },
      { code: '307', location: 'Cheyenne, WY' },
      { code: '308', location: 'North Platte, NE' },
      { code: '309', location: 'Peoria, IL' },
      { code: '310', location: 'Los Angeles, CA' },
      { code: '312', location: 'Chicago, IL' },
      { code: '313', location: 'Detroit, MI' },
      { code: '314', location: 'St. Louis, MO' },
      { code: '315', location: 'Syracuse, NY' },
      { code: '316', location: 'Wichita, KS' },
      { code: '317', location: 'Indianapolis, IN' },
      { code: '318', location: 'Shreveport, LA' },
      { code: '319', location: 'Cedar Rapids, IA' },
      { code: '320', location: 'St. Cloud, MN' },
      { code: '321', location: 'Orlando, FL' },
      { code: '323', location: 'Los Angeles, CA' },
      { code: '325', location: 'Abilene, TX' },
      { code: '330', location: 'Akron, OH' },
      { code: '334', location: 'Montgomery, AL' },
      { code: '336', location: 'Greensboro, NC' },
      { code: '337', location: 'Lafayette, LA' },
      { code: '339', location: 'Boston, MA' },
      { code: '346', location: 'Houston, TX' },
      { code: '347', location: 'Brooklyn, NY' },
      { code: '351', location: 'Lowell, MA' },
      { code: '352', location: 'Gainesville, FL' },
      { code: '360', location: 'Olympia, WA' },
      { code: '361', location: 'Corpus Christi, TX' },
      { code: '385', location: 'Salt Lake City, UT' },
      { code: '386', location: 'Daytona Beach, FL' },
      { code: '401', location: 'Providence, RI' },
      { code: '402', location: 'Omaha, NE' },
      { code: '404', location: 'Atlanta, GA' },
      { code: '405', location: 'Oklahoma City, OK' },
      { code: '406', location: 'Billings, MT' },
      { code: '407', location: 'Orlando, FL' },
      { code: '408', location: 'San Jose, CA' },
      { code: '409', location: 'Beaumont, TX' },
      { code: '410', location: 'Baltimore, MD' },
      { code: '412', location: 'Pittsburgh, PA' },
      { code: '413', location: 'Springfield, MA' },
      { code: '414', location: 'Milwaukee, WI' },
      { code: '415', location: 'San Francisco, CA' },
      { code: '417', location: 'Springfield, MO' },
      { code: '419', location: 'Toledo, OH' },
      { code: '423', location: 'Chattanooga, TN' },
      { code: '424', location: 'Los Angeles, CA' },
      { code: '425', location: 'Bellevue, WA' },
      { code: '430', location: 'Tyler, TX' },
      { code: '432', location: 'Midland, TX' },
      { code: '434', location: 'Lynchburg, VA' },
      { code: '435', location: 'St. George, UT' },
      { code: '440', location: 'Cleveland, OH' },
      { code: '442', location: 'Oceanside, CA' },
      { code: '443', location: 'Baltimore, MD' },
      { code: '469', location: 'Dallas, TX' },
      { code: '470', location: 'Atlanta, GA' },
      { code: '475', location: 'Bridgeport, CT' },
      { code: '478', location: 'Macon, GA' },
      { code: '479', location: 'Fayetteville, AR' },
      { code: '480', location: 'Phoenix, AZ' },
      { code: '484', location: 'Allentown, PA' },
      { code: '501', location: 'Little Rock, AR' },
      { code: '502', location: 'Louisville, KY' },
      { code: '503', location: 'Portland, OR' },
      { code: '504', location: 'New Orleans, LA' },
      { code: '505', location: 'Albuquerque, NM' },
      { code: '507', location: 'Rochester, MN' },
      { code: '508', location: 'Worcester, MA' },
      { code: '509', location: 'Spokane, WA' },
      { code: '510', location: 'Oakland, CA' },
      { code: '512', location: 'Austin, TX' },
      { code: '513', location: 'Cincinnati, OH' },
      { code: '515', location: 'Des Moines, IA' },
      { code: '516', location: 'Hempstead, NY' },
      { code: '517', location: 'Lansing, MI' },
      { code: '518', location: 'Albany, NY' },
      { code: '520', location: 'Tucson, AZ' },
      { code: '530', location: 'Redding, CA' },
      { code: '540', location: 'Roanoke, VA' },
      { code: '541', location: 'Eugene, OR' },
      { code: '559', location: 'Fresno, CA' },
      { code: '561', location: 'West Palm Beach, FL' },
      { code: '562', location: 'Long Beach, CA' },
      { code: '563', location: 'Davenport, IA' },
      { code: '567', location: 'Toledo, OH' },
      { code: '570', location: 'Scranton, PA' },
      { code: '571', location: 'Arlington, VA' },
      { code: '573', location: 'Columbia, MO' },
      { code: '574', location: 'South Bend, IN' },
      { code: '575', location: 'Las Cruces, NM' },
      { code: '580', location: 'Lawton, OK' },
      { code: '585', location: 'Rochester, NY' },
      { code: '586', location: 'Warren, MI' },
      { code: '601', location: 'Jackson, MS' },
      { code: '602', location: 'Phoenix, AZ' },
      { code: '603', location: 'Manchester, NH' },
      { code: '605', location: 'Sioux Falls, SD' },
      { code: '606', location: 'Ashland, KY' },
      { code: '607', location: 'Binghamton, NY' },
      { code: '608', location: 'Madison, WI' },
      { code: '609', location: 'Trenton, NJ' },
      { code: '610', location: 'Allentown, PA' },
      { code: '612', location: 'Minneapolis, MN' },
      { code: '614', location: 'Columbus, OH' },
      { code: '615', location: 'Nashville, TN' },
      { code: '616', location: 'Grand Rapids, MI' },
      { code: '617', location: 'Boston, MA' },
      { code: '618', location: 'Belleville, IL' },
      { code: '619', location: 'San Diego, CA' },
      { code: '620', location: 'Hutchinson, KS' },
      { code: '623', location: 'Phoenix, AZ' },
      { code: '626', location: 'Pasadena, CA' },
      { code: '630', location: 'Aurora, IL' },
      { code: '631', location: 'Brentwood, NY' },
      { code: '636', location: 'O\'Fallon, MO' },
      { code: '641', location: 'Mason City, IA' },
      { code: '646', location: 'Manhattan, NY' },
      { code: '650', location: 'San Mateo, CA' },
      { code: '651', location: 'St. Paul, MN' },
      { code: '657', location: 'Anaheim, CA' },
      { code: '660', location: 'Sedalia, MO' },
      { code: '661', location: 'Bakersfield, CA' },
      { code: '662', location: 'Tupelo, MS' },
      { code: '667', location: 'Baltimore, MD' },
      { code: '669', location: 'San Jose, CA' },
      { code: '678', location: 'Atlanta, GA' },
      { code: '681', location: 'Charleston, WV' },
      { code: '682', location: 'Fort Worth, TX' },
      { code: '701', location: 'Fargo, ND' },
      { code: '702', location: 'Las Vegas, NV' },
      { code: '703', location: 'Arlington, VA' },
      { code: '704', location: 'Charlotte, NC' },
      { code: '706', location: 'Augusta, GA' },
      { code: '707', location: 'Santa Rosa, CA' },
      { code: '708', location: 'Cicero, IL' },
      { code: '712', location: 'Sioux City, IA' },
      { code: '713', location: 'Houston, TX' },
      { code: '714', location: 'Anaheim, CA' },
      { code: '715', location: 'Eau Claire, WI' },
      { code: '716', location: 'Buffalo, NY' },
      { code: '717', location: 'Harrisburg, PA' },
      { code: '718', location: 'Brooklyn, NY' },
      { code: '719', location: 'Colorado Springs, CO' },
      { code: '720', location: 'Denver, CO' },
      { code: '724', location: 'New Castle, PA' },
      { code: '725', location: 'Las Vegas, NV' },
      { code: '727', location: 'St. Petersburg, FL' },
      { code: '731', location: 'Jackson, TN' },
      { code: '732', location: 'Toms River, NJ' },
      { code: '734', location: 'Ann Arbor, MI' },
      { code: '737', location: 'Austin, TX' },
      { code: '740', location: 'Zanesville, OH' },
      { code: '747', location: 'Los Angeles, CA' },
      { code: '754', location: 'Fort Lauderdale, FL' },
      { code: '757', location: 'Virginia Beach, VA' },
      { code: '760', location: 'Oceanside, CA' },
      { code: '763', location: 'Brooklyn Park, MN' },
      { code: '765', location: 'Muncie, IN' },
      { code: '769', location: 'Jackson, MS' },
      { code: '770', location: 'Atlanta, GA' },
      { code: '772', location: 'Port St. Lucie, FL' },
      { code: '773', location: 'Chicago, IL' },
      { code: '774', location: 'Worcester, MA' },
      { code: '775', location: 'Reno, NV' },
      { code: '779', location: 'Rockford, IL' },
      { code: '781', location: 'Boston, MA' },
      { code: '785', location: 'Topeka, KS' },
      { code: '786', location: 'Miami, FL' },
      { code: '801', location: 'Salt Lake City, UT' },
      { code: '802', location: 'Burlington, VT' },
      { code: '803', location: 'Columbia, SC' },
      { code: '804', location: 'Richmond, VA' },
      { code: '805', location: 'Oxnard, CA' },
      { code: '806', location: 'Lubbock, TX' },
      { code: '808', location: 'Honolulu, HI' },
      { code: '810', location: 'Flint, MI' },
      { code: '812', location: 'Evansville, IN' },
      { code: '813', location: 'Tampa, FL' },
      { code: '814', location: 'Erie, PA' },
      { code: '815', location: 'Rockford, IL' },
      { code: '816', location: 'Kansas City, MO' },
      { code: '817', location: 'Fort Worth, TX' },
      { code: '818', location: 'Los Angeles, CA' },
      { code: '828', location: 'Asheville, NC' },
      { code: '830', location: 'New Braunfels, TX' },
      { code: '831', location: 'Salinas, CA' },
      { code: '832', location: 'Houston, TX' },
      { code: '843', location: 'Charleston, SC' },
      { code: '845', location: 'Poughkeepsie, NY' },
      { code: '847', location: 'Evanston, IL' },
      { code: '850', location: 'Tallahassee, FL' },
      { code: '856', location: 'Camden, NJ' },
      { code: '857', location: 'Boston, MA' },
      { code: '858', location: 'San Diego, CA' },
      { code: '859', location: 'Lexington, KY' },
      { code: '860', location: 'Hartford, CT' },
      { code: '862', location: 'Newark, NJ' },
      { code: '863', location: 'Lakeland, FL' },
      { code: '864', location: 'Greenville, SC' },
      { code: '865', location: 'Knoxville, TN' },
      { code: '870', location: 'Jonesboro, AR' },
      { code: '872', location: 'Chicago, IL' },
      { code: '901', location: 'Memphis, TN' },
      { code: '903', location: 'Tyler, TX' },
      { code: '904', location: 'Jacksonville, FL' },
      { code: '906', location: 'Marquette, MI' },
      { code: '907', location: 'Anchorage, AK' },
      { code: '908', location: 'Elizabeth, NJ' },
      { code: '909', location: 'San Bernardino, CA' },
      { code: '910', location: 'Fayetteville, NC' },
      { code: '912', location: 'Savannah, GA' },
      { code: '913', location: 'Kansas City, KS' },
      { code: '914', location: 'Yonkers, NY' },
      { code: '915', location: 'El Paso, TX' },
      { code: '916', location: 'Sacramento, CA' },
      { code: '917', location: 'New York City, NY' },
      { code: '918', location: 'Tulsa, OK' },
      { code: '919', location: 'Raleigh, NC' },
      { code: '920', location: 'Green Bay, WI' },
      { code: '925', location: 'Concord, CA' },
      { code: '928', location: 'Flagstaff, AZ' },
      { code: '929', location: 'Queens, NY' },
      { code: '931', location: 'Clarksville, TN' },
      { code: '936', location: 'Conroe, TX' },
      { code: '937', location: 'Dayton, OH' },
      { code: '940', location: 'Wichita Falls, TX' },
      { code: '941', location: 'Sarasota, FL' },
      { code: '947', location: 'Troy, MI' },
      { code: '949', location: 'Irvine, CA' },
      { code: '951', location: 'Riverside, CA' },
      { code: '952', location: 'Bloomington, MN' },
      { code: '954', location: 'Fort Lauderdale, FL' },
      { code: '956', location: 'Laredo, TX' },
      { code: '970', location: 'Fort Collins, CO' },
      { code: '971', location: 'Portland, OR' },
      { code: '972', location: 'Dallas, TX' },
      { code: '973', location: 'Newark, NJ' },
      { code: '978', location: 'Lowell, MA' },
      { code: '979', location: 'Bryan, TX' },
      { code: '980', location: 'Charlotte, NC' },
      { code: '984', location: 'Raleigh, NC' },
      { code: '985', location: 'Houma, LA' },
      { code: '986', location: 'Boise, ID' },
      { code: '989', location: 'Saginaw, MI' },
      // Recent additions (2020-2024)
      { code: '223', location: 'Lancaster, PA' },
      { code: '227', location: 'Silver Spring, MD' },
      { code: '235', location: 'Oklahoma City, OK' },
      { code: '272', location: 'Scranton, PA' },
      { code: '274', location: 'Green Bay, WI' },
      { code: '279', location: 'Sacramento, CA' },
      { code: '326', location: 'Dayton, OH' },
      { code: '332', location: 'Manhattan, NY' },
      { code: '341', location: 'Oakland, CA' },
      { code: '350', location: 'San Francisco, CA' },
      { code: '353', location: 'Worcester, MA' },
      { code: '354', location: 'Killeen, TX' },
      { code: '363', location: 'Hempstead, NY' },
      { code: '364', location: 'Bowling Green, KY' },
      { code: '380', location: 'Columbus, OH' },
      { code: '428', location: 'Scranton, PA' },
      { code: '436', location: 'Richmond, VA' },
      { code: '445', location: 'Philadelphia, PA' },
      { code: '448', location: 'Orlando, FL' },
      { code: '458', location: 'Eugene, OR' },
      { code: '463', location: 'Indianapolis, IN' },
      { code: '464', location: 'Chicago, IL' },
      { code: '468', location: 'Quebec, QC' },
      { code: '472', location: 'Raleigh, NC' },
      { code: '474', location: 'Anchorage, AK' },
      { code: '513', location: 'Cincinnati, OH' },
      { code: '539', location: 'Tulsa, OK' },
      { code: '564', location: 'Seattle, WA' },
      { code: '582', location: 'Erie, PA' },
      { code: '629', location: 'Nashville, TN' },
      { code: '640', location: 'Atlantic City, NJ' },
      { code: '656', location: 'St. Petersburg, FL' },
      { code: '659', location: 'Birmingham, AL' },
      { code: '680', location: 'Syracuse, NY' },
      { code: '683', location: 'Fredericksburg, VA' },
      { code: '689', location: 'Orlando, FL' },
      { code: '726', location: 'San Antonio, TX' },
      { code: '728', location: 'St. Petersburg, FL' },
      { code: '730', location: 'Rockford, IL' },
      { code: '738', location: 'Hamilton, ON' },
      { code: '743', location: 'Greensboro, NC' },
      { code: '753', location: 'Ottawa, ON' },
      { code: '762', location: 'Augusta, GA' },
      { code: '771', location: 'Washington, DC' },
      { code: '820', location: 'San Diego, CA' },
      { code: '826', location: 'Fredericksburg, VA' },
      { code: '838', location: 'Saratoga Springs, NY' },
      { code: '840', location: 'Orange County, CA' },
      { code: '854', location: 'Charleston, SC' },
      { code: '878', location: 'Pittsburgh, PA' },
      { code: '879', location: 'Syracuse, NY' },
      { code: '881', location: 'Toll-Free' },
      { code: '882', location: 'Toll-Free' },
      { code: '883', location: 'Toll-Free' },
      { code: '884', location: 'Toll-Free' },
      { code: '885', location: 'Toll-Free' },
      { code: '886', location: 'Toll-Free' },
      { code: '887', location: 'Toll-Free' },
      { code: '889', location: 'Toll-Free' },
      { code: '938', location: 'Huntsville, AL' },
      { code: '943', location: 'Augusta, GA' },
      { code: '945', location: 'Dallas, TX' },
      { code: '948', location: 'Richmond, VA' },
      { code: '959', location: 'Hartford, CT' },
      { code: '983', location: 'Denver, CO' },
      // Additional missing area codes
      { code: '220', location: 'Newark, OH' },
      { code: '283', location: 'Cincinnati, OH' },
      { code: '324', location: 'Abilene, TX' },
      { code: '327', location: 'Little Rock, AR' },
      { code: '329', location: 'Rochester, NY' },
      { code: '331', location: 'Aurora, IL' },
      { code: '332', location: 'New York, NY' },
      { code: '342', location: 'Boston, MA' },
      { code: '344', location: 'Corpus Christi, TX' },
      { code: '348', location: 'Buffalo, NY' },
      { code: '349', location: 'Pensacola, FL' },
      { code: '350', location: 'San Francisco, CA' },
      { code: '356', location: 'Pueblo, CO' },
      { code: '359', location: 'Savannah, GA' },
      { code: '363', location: 'Long Island, NY' },
      { code: '367', location: 'Quebec, QC' },
      { code: '368', location: 'Montreal, QC' },
      { code: '369', location: 'Napa, CA' },
      { code: '380', location: 'Columbus, OH' },
      { code: '382', location: 'Ontario, ON' },
      { code: '387', location: 'Fresno, CA' },
      { code: '389', location: 'Detroit, MI' },
      { code: '411', location: 'Directory Assistance' },
      { code: '426', location: 'Houston, TX' },
      { code: '428', location: 'Scranton, PA' },
      { code: '429', location: 'Nashville, TN' },
      { code: '436', location: 'Richmond, VA' },
      { code: '445', location: 'Philadelphia, PA' },
      { code: '447', location: 'Springfield, IL' },
      { code: '448', location: 'Orlando, FL' },
      { code: '454', location: 'Rockford, IL' },
      { code: '458', location: 'Eugene, OR' },
      { code: '463', location: 'Indianapolis, IN' },
      { code: '464', location: 'Chicago, IL' },
      { code: '468', location: 'Quebec, QC' },
      { code: '472', location: 'Raleigh, NC' },
      { code: '474', location: 'Anchorage, AK' },
      { code: '479', location: 'Fort Smith, AR' },
      { code: '487', location: 'Lansing, MI' },
      { code: '513', location: 'Cincinnati, OH' },
      { code: '524', location: 'Atlanta, GA' },
      { code: '525', location: 'Seattle, WA' },
      { code: '526', location: 'Phoenix, AZ' },
      { code: '527', location: 'Orlando, FL' },
      { code: '528', location: 'Phoenix, AZ' },
      { code: '529', location: 'Riverside, CA' },
      { code: '531', location: 'Omaha, NE' },
      { code: '534', location: 'Eau Claire, WI' },
      { code: '539', location: 'Tulsa, OK' },
      { code: '542', location: 'Ontario, ON' },
      { code: '543', location: 'Eugene, OR' },
      { code: '544', location: 'Riverside, CA' },
      { code: '545', location: 'Tacoma, WA' },
      { code: '546', location: 'Ontario, ON' },
      { code: '547', location: 'South Bend, IN' },
      { code: '548', location: 'Ontario, ON' },
      { code: '549', location: 'Stockton, CA' },
      { code: '551', location: 'Jersey City, NJ' },
      { code: '553', location: 'Tampa, FL' },
      { code: '554', location: 'Fresno, CA' },
      { code: '556', location: 'Des Moines, IA' },
      { code: '557', location: 'St. Louis, MO' },
      { code: '558', location: 'Fresno, CA' },
      { code: '564', location: 'Seattle, WA' },
      { code: '566', location: 'Riverside, CA' },
      { code: '572', location: 'Tulsa, OK' },
      { code: '576', location: 'Sarasota, FL' },
      { code: '577', location: 'Reno, NV' },
      { code: '578', location: 'Quebec, QC' },
      { code: '579', location: 'Quebec, QC' },
      { code: '582', location: 'Erie, PA' },
      { code: '584', location: 'Manitoba, MB' },
      { code: '588', location: 'Victoria, BC' },
      { code: '592', location: 'Savannah, GA' },
      { code: '594', location: 'Montgomery, AL' },
      { code: '600', location: 'Canadian Services' },
      { code: '629', location: 'Nashville, TN' },
      { code: '640', location: 'Atlantic City, NJ' },
      { code: '643', location: 'Ontario, ON' },
      { code: '645', location: 'Buffalo, NY' },
      { code: '656', location: 'St. Petersburg, FL' },
      { code: '659', location: 'Birmingham, AL' },
      { code: '664', location: 'Montserrat' },
      { code: '670', location: 'Northern Mariana Islands' },
      { code: '671', location: 'Guam' },
      { code: '672', location: 'Vancouver, BC' },
      { code: '680', location: 'Syracuse, NY' },
      { code: '681', location: 'Charleston, WV' },
      { code: '683', location: 'Fredericksburg, VA' },
      { code: '684', location: 'American Samoa' },
      { code: '689', location: 'Orlando, FL' },
      { code: '721', location: 'Sint Maarten' },
      { code: '726', location: 'San Antonio, TX' },
      { code: '728', location: 'St. Petersburg, FL' },
      { code: '730', location: 'Rockford, IL' },
      { code: '737', location: 'Austin, TX' },
      { code: '738', location: 'Hamilton, ON' },
      { code: '742', location: 'Ontario, ON' },
      { code: '743', location: 'Greensboro, NC' },
      { code: '753', location: 'Ottawa, ON' },
      { code: '758', location: 'St. Lucia' },
      { code: '762', location: 'Augusta, GA' },
      { code: '767', location: 'Dominica' },
      { code: '768', location: 'Montreal, QC' },
      { code: '771', location: 'Washington, DC' },
      { code: '784', location: 'St. Vincent & Grenadines' },
      { code: '787', location: 'Puerto Rico' },
      { code: '820', location: 'San Diego, CA' },
      { code: '826', location: 'Fredericksburg, VA' },
      { code: '829', location: 'Dominican Republic' },
      { code: '838', location: 'Saratoga Springs, NY' },
      { code: '839', location: 'South Carolina' },
      { code: '840', location: 'Orange County, CA' },
      { code: '849', location: 'Dominican Republic' },
      { code: '854', location: 'Charleston, SC' },
      { code: '867', location: 'Yukon, NT, NU' },
      { code: '868', location: 'Trinidad & Tobago' },
      { code: '869', location: 'St. Kitts & Nevis' },
      { code: '876', location: 'Jamaica' },
      { code: '878', location: 'Pittsburgh, PA' },
      { code: '879', location: 'Syracuse, NY' },
    ],
    tollFree: [
      { code: '800', location: 'Toll-Free' },
      { code: '888', location: 'Toll-Free' },
      { code: '877', location: 'Toll-Free' },
      { code: '866', location: 'Toll-Free' },
      { code: '855', location: 'Toll-Free' },
      { code: '844', location: 'Toll-Free' },
      { code: '833', location: 'Toll-Free' },
    ],
  },
  uk: {
    code: '44',
    areaCodes: [
      { code: '20', location: 'London' },
      { code: '121', location: 'Birmingham' },
      { code: '131', location: 'Edinburgh' },
      { code: '141', location: 'Glasgow' },
      { code: '151', location: 'Liverpool' },
      { code: '161', location: 'Manchester' },
      { code: '113', location: 'Leeds' },
      { code: '114', location: 'Sheffield' },
      { code: '115', location: 'Nottingham' },
      { code: '116', location: 'Leicester' },
      { code: '117', location: 'Bristol' },
      { code: '118', location: 'Reading' },
      { code: '1223', location: 'Cambridge' },
      { code: '1224', location: 'Aberdeen' },
      { code: '1225', location: 'Bath' },
      { code: '1226', location: 'Barnsley' },
      { code: '1227', location: 'Canterbury' },
      { code: '1228', location: 'Carlisle' },
      { code: '1233', location: 'Ashford' },
      { code: '1234', location: 'Bedford' },
      { code: '1235', location: 'Abingdon' },
      { code: '1242', location: 'Cheltenham' },
      { code: '1243', location: 'Chichester' },
      { code: '1244', location: 'Chester' },
      { code: '1245', location: 'Chelmsford' },
      { code: '1246', location: 'Chesterfield' },
      { code: '1252', location: 'Aldershot' },
      { code: '1253', location: 'Blackpool' },
      { code: '1254', location: 'Blackburn' },
      { code: '1256', location: 'Basingstoke' },
      { code: '1273', location: 'Brighton' },
      { code: '1274', location: 'Bradford' },
      { code: '1275', location: 'Bristol' },
      { code: '1276', location: 'Camberley' },
      { code: '1277', location: 'Brentwood' },
      { code: '1278', location: 'Bridgwater' },
      { code: '1279', location: 'Harlow' },
      { code: '1282', location: 'Burnley' },
      { code: '1283', location: 'Burton-on-Trent' },
      { code: '1284', location: 'Bury St Edmunds' },
      { code: '1285', location: 'Cirencester' },
      { code: '1291', location: 'Chepstow' },
      { code: '1292', location: 'Ayr' },
      { code: '1293', location: 'Crawley' },
      { code: '1294', location: 'Ardrossan' },
      { code: '1295', location: 'Banbury' },
      { code: '1296', location: 'Aylesbury' },
      { code: '1297', location: 'Axminster' },
      { code: '1298', location: 'Buxton' },
      { code: '1299', location: 'Bewdley' },
    ],
    mobile: [
      { code: '7400', location: 'Mobile' },
      { code: '7401', location: 'Mobile' },
      { code: '7402', location: 'Mobile' },
      { code: '7403', location: 'Mobile' },
      { code: '7500', location: 'Mobile' },
      { code: '7501', location: 'Mobile' },
      { code: '7502', location: 'Mobile' },
      { code: '7503', location: 'Mobile' },
      { code: '7700', location: 'Mobile' },
      { code: '7701', location: 'Mobile' },
      { code: '7702', location: 'Mobile' },
      { code: '7800', location: 'Mobile' },
      { code: '7801', location: 'Mobile' },
      { code: '7900', location: 'Mobile' },
      { code: '7901', location: 'Mobile' },
    ],
    tollFree: [
      { code: '800', location: 'Toll-Free' },
      { code: '808', location: 'Toll-Free' },
    ],
  },
  canada: {
    code: '1',
    areaCodes: [
      { code: '204', location: 'Winnipeg, MB' },
      { code: '226', location: 'London, ON' },
      { code: '236', location: 'Vancouver, BC' },
      { code: '249', location: 'Sudbury, ON' },
      { code: '250', location: 'Victoria, BC' },
      { code: '289', location: 'Hamilton, ON' },
      { code: '306', location: 'Regina, SK' },
      { code: '343', location: 'Ottawa, ON' },
      { code: '365', location: 'Hamilton, ON' },
      { code: '403', location: 'Calgary, AB' },
      { code: '416', location: 'Toronto, ON' },
      { code: '418', location: 'Quebec City, QC' },
      { code: '431', location: 'Winnipeg, MB' },
      { code: '437', location: 'Toronto, ON' },
      { code: '438', location: 'Montreal, QC' },
      { code: '450', location: 'Laval, QC' },
      { code: '506', location: 'Moncton, NB' },
      { code: '514', location: 'Montreal, QC' },
      { code: '519', location: 'London, ON' },
      { code: '548', location: 'Kitchener, ON' },
      { code: '579', location: 'Laval, QC' },
      { code: '581', location: 'Quebec City, QC' },
      { code: '587', location: 'Calgary, AB' },
      { code: '604', location: 'Vancouver, BC' },
      { code: '613', location: 'Ottawa, ON' },
      { code: '639', location: 'Regina, SK' },
      { code: '647', location: 'Toronto, ON' },
      { code: '672', location: 'Vancouver, BC' },
      { code: '705', location: 'Barrie, ON' },
      { code: '709', location: "St. John's, NL" },
      { code: '778', location: 'Vancouver, BC' },
      { code: '780', location: 'Edmonton, AB' },
      { code: '782', location: 'Halifax, NS' },
      { code: '807', location: 'Thunder Bay, ON' },
      { code: '819', location: 'Gatineau, QC' },
      { code: '825', location: 'Edmonton, AB' },
      { code: '867', location: 'Yukon, NT, NU' },
      { code: '873', location: 'Montreal, QC' },
      { code: '902', location: 'Halifax, NS' },
      { code: '905', location: 'Mississauga, ON' },
    ],
    tollFree: [
      { code: '800', location: 'Toll-Free' },
      { code: '888', location: 'Toll-Free' },
      { code: '877', location: 'Toll-Free' },
      { code: '866', location: 'Toll-Free' },
      { code: '855', location: 'Toll-Free' },
      { code: '844', location: 'Toll-Free' },
      { code: '833', location: 'Toll-Free' },
    ],
  },
  australia: {
    code: '61',
    areaCodes: [
      { code: '2', location: 'Sydney, NSW' },
      { code: '3', location: 'Melbourne, VIC' },
      { code: '7', location: 'Brisbane, QLD' },
      { code: '8', location: 'Adelaide, SA / Perth, WA' },
    ],
    mobile: [
      // Complete Australian Mobile Prefixes (04XX range)
      // Telstra
      { code: '0400', location: 'Mobile - Telstra' },
      { code: '0401', location: 'Mobile - Telstra' },
      { code: '0402', location: 'Mobile - Telstra' },
      { code: '0403', location: 'Mobile - Telstra' },
      { code: '0404', location: 'Mobile - Telstra' },
      { code: '0405', location: 'Mobile - Telstra' },
      { code: '0406', location: 'Mobile - Telstra' },
      { code: '0407', location: 'Mobile - Telstra' },
      { code: '0408', location: 'Mobile - Telstra' },
      { code: '0409', location: 'Mobile - Telstra' },
      { code: '0418', location: 'Mobile - Telstra' },
      { code: '0419', location: 'Mobile - Telstra' },
      { code: '0428', location: 'Mobile - Telstra' },
      { code: '0429', location: 'Mobile - Telstra' },
      { code: '0438', location: 'Mobile - Telstra' },
      { code: '0439', location: 'Mobile - Telstra' },
      { code: '0448', location: 'Mobile - Telstra' },
      { code: '0449', location: 'Mobile - Telstra' },
      { code: '0458', location: 'Mobile - Telstra' },
      { code: '0459', location: 'Mobile - Telstra' },
      { code: '0468', location: 'Mobile - Telstra' },
      { code: '0469', location: 'Mobile - Telstra' },
      { code: '0478', location: 'Mobile - Telstra' },
      { code: '0479', location: 'Mobile - Telstra' },
      { code: '0488', location: 'Mobile - Telstra' },
      { code: '0489', location: 'Mobile - Telstra' },
      // Optus
      { code: '0410', location: 'Mobile - Optus' },
      { code: '0411', location: 'Mobile - Optus' },
      { code: '0412', location: 'Mobile - Optus' },
      { code: '0413', location: 'Mobile - Optus' },
      { code: '0414', location: 'Mobile - Optus' },
      { code: '0415', location: 'Mobile - Optus' },
      { code: '0421', location: 'Mobile - Optus' },
      { code: '0422', location: 'Mobile - Optus' },
      { code: '0423', location: 'Mobile - Optus' },
      { code: '0424', location: 'Mobile - Optus' },
      { code: '0425', location: 'Mobile - Optus' },
      { code: '0431', location: 'Mobile - Optus' },
      { code: '0432', location: 'Mobile - Optus' },
      { code: '0433', location: 'Mobile - Optus' },
      { code: '0434', location: 'Mobile - Optus' },
      { code: '0435', location: 'Mobile - Optus' },
      { code: '0441', location: 'Mobile - Optus' },
      { code: '0442', location: 'Mobile - Optus' },
      { code: '0443', location: 'Mobile - Optus' },
      { code: '0444', location: 'Mobile - Optus' },
      { code: '0445', location: 'Mobile - Optus' },
      { code: '0451', location: 'Mobile - Optus' },
      { code: '0452', location: 'Mobile - Optus' },
      { code: '0453', location: 'Mobile - Optus' },
      { code: '0454', location: 'Mobile - Optus' },
      { code: '0455', location: 'Mobile - Optus' },
      { code: '0461', location: 'Mobile - Optus' },
      { code: '0462', location: 'Mobile - Optus' },
      { code: '0463', location: 'Mobile - Optus' },
      { code: '0464', location: 'Mobile - Optus' },
      { code: '0465', location: 'Mobile - Optus' },
      { code: '0471', location: 'Mobile - Optus' },
      { code: '0472', location: 'Mobile - Optus' },
      { code: '0473', location: 'Mobile - Optus' },
      { code: '0474', location: 'Mobile - Optus' },
      { code: '0475', location: 'Mobile - Optus' },
      { code: '0481', location: 'Mobile - Optus' },
      { code: '0482', location: 'Mobile - Optus' },
      { code: '0483', location: 'Mobile - Optus' },
      { code: '0484', location: 'Mobile - Optus' },
      { code: '0485', location: 'Mobile - Optus' },
      // Vodafone
      { code: '0416', location: 'Mobile - Vodafone' },
      { code: '0417', location: 'Mobile - Vodafone' },
      { code: '0420', location: 'Mobile - Vodafone' },
      { code: '0426', location: 'Mobile - Vodafone' },
      { code: '0427', location: 'Mobile - Vodafone' },
      { code: '0430', location: 'Mobile - Vodafone' },
      { code: '0436', location: 'Mobile - Vodafone' },
      { code: '0437', location: 'Mobile - Vodafone' },
      { code: '0440', location: 'Mobile - Vodafone' },
      { code: '0446', location: 'Mobile - Vodafone' },
      { code: '0447', location: 'Mobile - Vodafone' },
      { code: '0450', location: 'Mobile - Vodafone' },
      { code: '0456', location: 'Mobile - Vodafone' },
      { code: '0457', location: 'Mobile - Vodafone' },
      { code: '0460', location: 'Mobile - Vodafone' },
      { code: '0466', location: 'Mobile - Vodafone' },
      { code: '0467', location: 'Mobile - Vodafone' },
      { code: '0470', location: 'Mobile - Vodafone' },
      { code: '0476', location: 'Mobile - Vodafone' },
      { code: '0477', location: 'Mobile - Vodafone' },
      { code: '0480', location: 'Mobile - Vodafone' },
      { code: '0486', location: 'Mobile - Vodafone' },
      { code: '0487', location: 'Mobile - Vodafone' },
      // MVNOs & Others
      { code: '0490', location: 'Mobile - MVNO' },
      { code: '0491', location: 'Mobile - MVNO' },
      { code: '0492', location: 'Mobile - MVNO' },
      { code: '0493', location: 'Mobile - MVNO' },
      { code: '0494', location: 'Mobile - MVNO' },
      { code: '0495', location: 'Mobile - MVNO' },
      { code: '0496', location: 'Mobile - MVNO' },
      { code: '0497', location: 'Mobile - MVNO' },
      { code: '0498', location: 'Mobile - MVNO' },
      { code: '0499', location: 'Mobile - MVNO' },
    ],
    tollFree: [
      { code: '1800', location: 'Toll-Free' },
    ],
  },
  germany: {
    code: '49',
    areaCodes: [
      { code: '30', location: 'Berlin' },
      { code: '40', location: 'Hamburg' },
      { code: '69', location: 'Frankfurt' },
      { code: '89', location: 'Munich' },
      { code: '201', location: 'Essen' },
      { code: '202', location: 'Wuppertal' },
      { code: '203', location: 'Duisburg' },
      { code: '209', location: 'Gelsenkirchen' },
      { code: '211', location: 'Düsseldorf' },
      { code: '221', location: 'Cologne' },
      { code: '228', location: 'Bonn' },
      { code: '231', location: 'Dortmund' },
      { code: '234', location: 'Bochum' },
      { code: '241', location: 'Aachen' },
      { code: '251', location: 'Münster' },
      { code: '261', location: 'Koblenz' },
      { code: '271', location: 'Siegen' },
      { code: '341', location: 'Leipzig' },
      { code: '351', location: 'Dresden' },
      { code: '361', location: 'Erfurt' },
      { code: '371', location: 'Chemnitz' },
      { code: '381', location: 'Rostock' },
      { code: '391', location: 'Magdeburg' },
      { code: '421', location: 'Bremen' },
      { code: '431', location: 'Oldenburg' },
      { code: '511', location: 'Hannover' },
      { code: '521', location: 'Bielefeld' },
      { code: '531', location: 'Braunschweig' },
      { code: '561', location: 'Kassel' },
      { code: '611', location: 'Wiesbaden' },
      { code: '621', location: 'Mannheim' },
      { code: '631', location: 'Kaiserslautern' },
      { code: '681', location: 'Saarbrücken' },
      { code: '711', location: 'Stuttgart' },
      { code: '721', location: 'Karlsruhe' },
      { code: '761', location: 'Freiburg' },
      { code: '821', location: 'Augsburg' },
      { code: '911', location: 'Nuremberg' },
      { code: '941', location: 'Regensburg' },
    ],
    mobile: [
      { code: '151', location: 'Mobile - T-Mobile' },
      { code: '152', location: 'Mobile - Vodafone' },
      { code: '157', location: 'Mobile - E-Plus' },
      { code: '159', location: 'Mobile - O2' },
      { code: '160', location: 'Mobile - T-Mobile' },
      { code: '162', location: 'Mobile - Vodafone' },
      { code: '170', location: 'Mobile - T-Mobile' },
      { code: '171', location: 'Mobile - T-Mobile' },
      { code: '172', location: 'Mobile - Vodafone' },
      { code: '173', location: 'Mobile - Vodafone' },
      { code: '174', location: 'Mobile - Vodafone' },
      { code: '175', location: 'Mobile - T-Mobile' },
      { code: '176', location: 'Mobile - O2' },
      { code: '177', location: 'Mobile - E-Plus' },
      { code: '178', location: 'Mobile - E-Plus' },
      { code: '179', location: 'Mobile - O2' },
    ],
    tollFree: [
      { code: '800', location: 'Toll-Free' },
    ],
  },
  france: {
    code: '33',
    areaCodes: [
      { code: '1', location: 'Paris & Île-de-France' },
      { code: '2', location: 'Northwest France' },
      { code: '3', location: 'Northeast France' },
      { code: '4', location: 'Southeast France' },
      { code: '5', location: 'Southwest France' },
    ],
    mobile: [
      { code: '6', location: 'Mobile' },
      { code: '7', location: 'Mobile' },
    ],
    tollFree: [
      { code: '800', location: 'Toll-Free' },
    ],
  },
  italy: {
    code: '39',
    areaCodes: [
      { code: '02', location: 'Milan' },
      { code: '06', location: 'Rome' },
      { code: '010', location: 'Genoa' },
      { code: '011', location: 'Turin' },
      { code: '030', location: 'Brescia' },
      { code: '031', location: 'Como' },
      { code: '035', location: 'Bergamo' },
      { code: '039', location: 'Monza' },
      { code: '040', location: 'Trieste' },
      { code: '041', location: 'Venice' },
      { code: '045', location: 'Verona' },
      { code: '049', location: 'Padua' },
      { code: '050', location: 'Pisa' },
      { code: '051', location: 'Bologna' },
      { code: '055', location: 'Florence' },
      { code: '059', location: 'Modena' },
      { code: '070', location: 'Cagliari' },
      { code: '071', location: 'Ancona' },
      { code: '075', location: 'Perugia' },
      { code: '079', location: 'Sassari' },
      { code: '080', location: 'Bari' },
      { code: '081', location: 'Naples' },
      { code: '085', location: 'Pescara' },
      { code: '089', location: 'Salerno' },
      { code: '090', location: 'Messina' },
      { code: '091', location: 'Palermo' },
      { code: '095', location: 'Catania' },
      { code: '099', location: 'Taranto' },
    ],
    mobile: [
      { code: '320', location: 'Mobile - Wind Tre' },
      { code: '330', location: 'Mobile - TIM' },
      { code: '331', location: 'Mobile - TIM' },
      { code: '333', location: 'Mobile - TIM' },
      { code: '334', location: 'Mobile - TIM' },
      { code: '335', location: 'Mobile - TIM' },
      { code: '336', location: 'Mobile - TIM' },
      { code: '337', location: 'Mobile - TIM' },
      { code: '338', location: 'Mobile - Wind Tre' },
      { code: '339', location: 'Mobile - Wind Tre' },
      { code: '340', location: 'Mobile - Vodafone' },
      { code: '342', location: 'Mobile - Vodafone' },
      { code: '343', location: 'Mobile - Vodafone' },
      { code: '345', location: 'Mobile - Vodafone' },
      { code: '346', location: 'Mobile - Vodafone' },
      { code: '347', location: 'Mobile - Vodafone' },
      { code: '348', location: 'Mobile - Vodafone' },
      { code: '349', location: 'Mobile - Vodafone' },
    ],
    tollFree: [
      { code: '800', location: 'Toll-Free' },
    ],
  },
  spain: {
    code: '34',
    areaCodes: [
      { code: '91', location: 'Madrid' },
      { code: '93', location: 'Barcelona' },
      { code: '95', location: 'Seville' },
      { code: '96', location: 'Valencia' },
      { code: '98', location: 'Bilbao' },
    ],
    mobile: [
      { code: '6', location: 'Mobile' },
      { code: '7', location: 'Mobile' },
    ],
    tollFree: [
      { code: '900', location: 'Toll-Free' },
    ],
  },
  netherlands: {
    code: '31',
    areaCodes: [
      { code: '10', location: 'Rotterdam' },
      { code: '13', location: 'Tilburg' },
      { code: '15', location: 'Delft' },
      { code: '20', location: 'Amsterdam' },
      { code: '23', location: 'Haarlem' },
      { code: '24', location: 'Nijmegen' },
      { code: '26', location: 'Arnhem' },
      { code: '30', location: 'Utrecht' },
      { code: '33', location: 'Amersfoort' },
      { code: '35', location: 'Hilversum' },
      { code: '36', location: 'Almere' },
      { code: '38', location: 'Zwolle' },
      { code: '40', location: 'Eindhoven' },
      { code: '43', location: 'Maastricht' },
      { code: '45', location: 'Heerlen' },
      { code: '46', location: 'Sittard' },
      { code: '50', location: 'Groningen' },
      { code: '53', location: 'Enschede' },
      { code: '55', location: 'Apeldoorn' },
      { code: '58', location: 'Leeuwarden' },
      { code: '70', location: 'The Hague' },
      { code: '71', location: 'Leiden' },
      { code: '72', location: 'Alkmaar' },
      { code: '73', location: "'s-Hertogenbosch" },
      { code: '74', location: 'Hengelo' },
      { code: '75', location: 'Zaandam' },
      { code: '76', location: 'Breda' },
      { code: '77', location: 'Venlo' },
      { code: '78', location: 'Dordrecht' },
      { code: '79', location: 'Zoetermeer' },
    ],
    mobile: [
      { code: '6', location: 'Mobile' },
    ],
    tollFree: [
      { code: '800', location: 'Toll-Free' },
    ],
  },
  sweden: {
    code: '46',
    areaCodes: [
      { code: '8', location: 'Stockholm' },
      { code: '11', location: 'Norrköping' },
      { code: '13', location: 'Linköping' },
      { code: '16', location: 'Eskilstuna' },
      { code: '18', location: 'Uppsala' },
      { code: '19', location: 'Örebro' },
      { code: '21', location: 'Västerås' },
      { code: '23', location: 'Falun' },
      { code: '26', location: 'Gävle' },
      { code: '31', location: 'Gothenburg' },
      { code: '33', location: 'Borås' },
      { code: '35', location: 'Halmstad' },
      { code: '36', location: 'Jönköping' },
      { code: '40', location: 'Malmö' },
      { code: '42', location: 'Helsingborg' },
      { code: '44', location: 'Kalmar' },
      { code: '46', location: 'Lund' },
      { code: '54', location: 'Karlstad' },
      { code: '60', location: 'Sundsvall' },
      { code: '63', location: 'Östersund' },
      { code: '90', location: 'Umeå' },
    ],
    mobile: [
      { code: '70', location: 'Mobile' },
      { code: '72', location: 'Mobile' },
      { code: '73', location: 'Mobile' },
      { code: '76', location: 'Mobile' },
      { code: '79', location: 'Mobile' },
    ],
    tollFree: [
      { code: '20', location: 'Toll-Free' },
    ],
  },
  norway: {
    code: '47',
    areaCodes: [
      { code: '21', location: 'Oslo' },
      { code: '22', location: 'Oslo' },
      { code: '23', location: 'Oslo' },
      { code: '51', location: 'Stavanger' },
      { code: '52', location: 'Haugesund' },
      { code: '53', location: 'Bergen' },
      { code: '55', location: 'Bergen' },
      { code: '61', location: 'Ålesund' },
      { code: '62', location: 'Molde' },
      { code: '63', location: 'Trondheim' },
      { code: '67', location: 'Lillehammer' },
      { code: '69', location: 'Hamar' },
      { code: '71', location: 'Kristiansund' },
      { code: '72', location: 'Trondheim' },
      { code: '73', location: 'Trondheim' },
      { code: '75', location: 'Bodø' },
      { code: '76', location: 'Narvik' },
      { code: '77', location: 'Tromsø' },
      { code: '78', location: 'Hammerfest' },
    ],
    mobile: [
      { code: '4', location: 'Mobile' },
      { code: '9', location: 'Mobile' },
    ],
    tollFree: [
      { code: '800', location: 'Toll-Free' },
    ],
  },
  denmark: {
    code: '45',
    areaCodes: [
      { code: '32', location: 'Copenhagen' },
      { code: '33', location: 'Copenhagen' },
      { code: '35', location: 'Copenhagen' },
      { code: '36', location: 'Frederiksberg' },
      { code: '38', location: 'Copenhagen' },
      { code: '39', location: 'Copenhagen' },
      { code: '43', location: 'Lyngby' },
      { code: '44', location: 'Glostrup' },
      { code: '45', location: 'Roskilde' },
      { code: '46', location: 'Helsingør' },
      { code: '47', location: 'Hillerød' },
      { code: '48', location: 'Næstved' },
      { code: '49', location: 'Nykøbing F' },
      { code: '53', location: 'Nykøbing F' },
      { code: '54', location: 'Nakskov' },
      { code: '55', location: 'Slagelse' },
      { code: '56', location: 'Holbæk' },
      { code: '57', location: 'Kalundborg' },
      { code: '58', location: 'Nykøbing Sj' },
      { code: '59', location: 'Svendborg' },
      { code: '62', location: 'Odense' },
      { code: '63', location: 'Middelfart' },
      { code: '64', location: 'Assens' },
      { code: '65', location: 'Odense' },
      { code: '66', location: 'Odense' },
      { code: '70', location: 'Fredericia' },
      { code: '72', location: 'Esbjerg' },
      { code: '73', location: 'Vejle' },
      { code: '74', location: 'Kolding' },
      { code: '75', location: 'Esbjerg' },
      { code: '76', location: 'Herning' },
      { code: '79', location: 'Skive' },
      { code: '86', location: 'Aarhus' },
      { code: '87', location: 'Aarhus' },
      { code: '89', location: 'Aarhus' },
      { code: '96', location: 'Aalborg' },
      { code: '97', location: 'Thisted' },
      { code: '98', location: 'Aalborg' },
      { code: '99', location: 'Hjørring' },
    ],
    mobile: [
      { code: '2', location: 'Mobile' },
      { code: '30', location: 'Mobile' },
      { code: '31', location: 'Mobile' },
      { code: '40', location: 'Mobile' },
      { code: '41', location: 'Mobile' },
      { code: '42', location: 'Mobile' },
      { code: '50', location: 'Mobile' },
      { code: '51', location: 'Mobile' },
      { code: '52', location: 'Mobile' },
      { code: '53', location: 'Mobile' },
      { code: '60', location: 'Mobile' },
      { code: '71', location: 'Mobile' },
      { code: '81', location: 'Mobile' },
      { code: '91', location: 'Mobile' },
      { code: '92', location: 'Mobile' },
      { code: '93', location: 'Mobile' },
    ],
    tollFree: [
      { code: '80', location: 'Toll-Free' },
    ],
  },
  india: {
    code: '91',
    areaCodes: [
      { code: '11', location: 'New Delhi' },
      { code: '22', location: 'Mumbai' },
      { code: '33', location: 'Kolkata' },
      { code: '40', location: 'Hyderabad' },
      { code: '44', location: 'Chennai' },
      { code: '79', location: 'Ahmedabad' },
      { code: '80', location: 'Bangalore' },
      { code: '120', location: 'Noida' },
      { code: '124', location: 'Gurgaon' },
      { code: '141', location: 'Jaipur' },
      { code: '172', location: 'Chandigarh' },
      { code: '181', location: 'Jammu' },
      { code: '191', location: 'Srinagar' },
      { code: '253', location: 'Dehradun' },
      { code: '261', location: 'Vadodara' },
      { code: '265', location: 'Indore' },
      { code: '278', location: 'Surat' },
      { code: '281', location: 'Ghaziabad' },
      { code: '291', location: 'Jodhpur' },
      { code: '343', location: 'Meerut' },
      { code: '361', location: 'Bhubaneswar' },
      { code: '381', location: 'Guwahati' },
      { code: '413', location: 'Solapur' },
      { code: '422', location: 'Nashik' },
      { code: '452', location: 'Indore' },
      { code: '471', location: 'Thiruvananthapuram' },
      { code: '484', location: 'Kochi' },
      { code: '512', location: 'Hyderabad' },
      { code: '522', location: 'Vijayawada' },
      { code: '542', location: 'Varanasi' },
      { code: '612', location: 'Patna' },
      { code: '651', location: 'Ranchi' },
      { code: '712', location: 'Asansol' },
      { code: '731', location: 'Raipur' },
      { code: '755', location: 'Bhopal' },
      { code: '761', location: 'Cuttack' },
      { code: '821', location: 'Gaya' },
      { code: '836', location: 'Dhanbad' },
    ],
    mobile: [
      { code: '6', location: 'Mobile' },
      { code: '7', location: 'Mobile' },
      { code: '8', location: 'Mobile' },
      { code: '9', location: 'Mobile' },
    ],
    tollFree: [
      { code: '1800', location: 'Toll-Free' },
    ],
  },
  japan: {
    code: '81',
    areaCodes: [
      { code: '3', location: 'Tokyo' },
      { code: '6', location: 'Osaka' },
      { code: '11', location: 'Sapporo' },
      { code: '22', location: 'Sendai' },
      { code: '25', location: 'Niigata' },
      { code: '45', location: 'Yokohama' },
      { code: '52', location: 'Nagoya' },
      { code: '75', location: 'Kyoto' },
      { code: '78', location: 'Kobe' },
      { code: '82', location: 'Hiroshima' },
      { code: '92', location: 'Fukuoka' },
      { code: '95', location: 'Nagasaki' },
      { code: '96', location: 'Kumamoto' },
      { code: '98', location: 'Naha' },
    ],
    mobile: [
      { code: '70', location: 'Mobile' },
      { code: '80', location: 'Mobile' },
      { code: '90', location: 'Mobile' },
    ],
    tollFree: [
      { code: '120', location: 'Toll-Free' },
    ],
  },
  china: {
    code: '86',
    areaCodes: [
      { code: '10', location: 'Beijing' },
      { code: '20', location: 'Guangzhou' },
      { code: '21', location: 'Shanghai' },
      { code: '22', location: 'Tianjin' },
      { code: '23', location: 'Chongqing' },
      { code: '24', location: 'Shenyang' },
      { code: '25', location: 'Nanjing' },
      { code: '27', location: 'Wuhan' },
      { code: '28', location: 'Chengdu' },
      { code: '29', location: "Xi'an" },
      { code: '311', location: 'Shijiazhuang' },
      { code: '351', location: 'Taiyuan' },
      { code: '371', location: 'Zhengzhou' },
      { code: '431', location: 'Changchun' },
      { code: '451', location: 'Harbin' },
      { code: '511', location: 'Chengdu' },
      { code: '531', location: 'Jinan' },
      { code: '551', location: 'Hefei' },
      { code: '571', location: 'Hangzhou' },
      { code: '591', location: 'Fuzhou' },
      { code: '731', location: 'Changsha' },
      { code: '755', location: 'Shenzhen' },
      { code: '791', location: 'Nanchang' },
      { code: '851', location: 'Guiyang' },
      { code: '871', location: 'Kunming' },
      { code: '891', location: 'Lhasa' },
    ],
    mobile: [
      { code: '130', location: 'Mobile - China Unicom' },
      { code: '131', location: 'Mobile - China Unicom' },
      { code: '132', location: 'Mobile - China Unicom' },
      { code: '133', location: 'Mobile - China Telecom' },
      { code: '134', location: 'Mobile - China Mobile' },
      { code: '135', location: 'Mobile - China Mobile' },
      { code: '136', location: 'Mobile - China Mobile' },
      { code: '137', location: 'Mobile - China Mobile' },
      { code: '138', location: 'Mobile - China Mobile' },
      { code: '139', location: 'Mobile - China Mobile' },
      { code: '150', location: 'Mobile - China Mobile' },
      { code: '151', location: 'Mobile - China Mobile' },
      { code: '152', location: 'Mobile - China Mobile' },
      { code: '153', location: 'Mobile - China Telecom' },
      { code: '155', location: 'Mobile - China Unicom' },
      { code: '156', location: 'Mobile - China Unicom' },
      { code: '157', location: 'Mobile - China Mobile' },
      { code: '158', location: 'Mobile - China Mobile' },
      { code: '159', location: 'Mobile - China Mobile' },
      { code: '180', location: 'Mobile - China Telecom' },
      { code: '181', location: 'Mobile - China Telecom' },
      { code: '182', location: 'Mobile - China Mobile' },
      { code: '183', location: 'Mobile - China Mobile' },
      { code: '184', location: 'Mobile - China Mobile' },
      { code: '185', location: 'Mobile - China Unicom' },
      { code: '186', location: 'Mobile - China Unicom' },
      { code: '187', location: 'Mobile - China Mobile' },
      { code: '188', location: 'Mobile - China Mobile' },
      { code: '189', location: 'Mobile - China Telecom' },
    ],
    tollFree: [
      { code: '400', location: 'Toll-Free' },
      { code: '800', location: 'Toll-Free' },
    ],
  },
};

const formatNumber = (countryCode, areaCode, number, format, country) => {
  const fullNumber = `${areaCode}${number}`;

  switch (format) {
    case 'formatted':
      if (countryCode === '1') {
        // USA/Canada: (XXX) XXX-XXXX
        return `(${areaCode}) ${number.substring(0, 3)}-${number.substring(3)}`;
      } else if (countryCode === '44') {
        // UK: XXXX XXXX XXXX
        return `${areaCode} ${number.substring(0, 4)} ${number.substring(4)}`;
      } else if (countryCode === '61') {
        // Australia: XXX XXX XXX
        return `${areaCode} ${number.substring(0, 3)} ${number.substring(3, 6)} ${number.substring(6)}`;
      } else if (countryCode === '49') {
        // Germany: XXX XXXXXXX
        return `${areaCode} ${number}`;
      } else if (countryCode === '33') {
        // France: X XX XX XX XX
        return `${areaCode} ${number.substring(0, 2)} ${number.substring(2, 4)} ${number.substring(4, 6)} ${number.substring(6)}`;
      } else if (countryCode === '39') {
        // Italy: XXX XXXXXXX
        return `${areaCode} ${number}`;
      } else if (countryCode === '34') {
        // Spain: XXX XXX XXX
        return `${areaCode} ${number.substring(0, 3)} ${number.substring(3, 6)} ${number.substring(6)}`;
      } else if (countryCode === '31') {
        // Netherlands: XX XXXXXXXX
        return `${areaCode} ${number}`;
      } else if (countryCode === '46') {
        // Sweden: XX XXX XXXX
        return `${areaCode} ${number.substring(0, 3)} ${number.substring(3)}`;
      } else if (countryCode === '47') {
        // Norway: XXX XX XXX
        return `${areaCode} ${number.substring(0, 2)} ${number.substring(2)}`;
      } else if (countryCode === '45') {
        // Denmark: XX XX XX XX
        return `${areaCode} ${number.substring(0, 2)} ${number.substring(2, 4)} ${number.substring(4)}`;
      } else if (countryCode === '91') {
        // India: XXXXX XXXXX
        return `${areaCode} ${number.substring(0, 5)} ${number.substring(5)}`;
      } else if (countryCode === '81') {
        // Japan: XX XXXX XXXX
        return `${areaCode} ${number.substring(0, 4)} ${number.substring(4)}`;
      } else if (countryCode === '86') {
        // China: XXX XXXX XXXX
        return `${areaCode} ${number.substring(0, 4)} ${number.substring(4)}`;
      } else {
        return `${areaCode} ${number}`;
      }
    case 'national':
      if (countryCode === '1') {
        return `(${areaCode}) ${number.substring(0, 3)}-${number.substring(3)}`;
      } else if (countryCode === '44') {
        return `${areaCode} ${number.substring(0, 4)} ${number.substring(4)}`;
      } else if (countryCode === '61') {
        return `${areaCode} ${number.substring(0, 3)} ${number.substring(3, 6)} ${number.substring(6)}`;
      } else {
        return `${areaCode} ${number}`;
      }
    case 'plain':
    default:
      return fullNumber.replace(/\s/g, '');
  }
};

const getTotalNumberLength = (country, numberType) => {
  // Returns total digits (area code + number) for each country
  const lengths = {
    usa: { mobile: 10, landline: 10, tollfree: 10 },
    uk: { mobile: 11, landline: 11, tollfree: 11 },
    canada: { mobile: 10, landline: 10, tollfree: 10 },
    australia: { mobile: 10, landline: 10, tollfree: 10 },
    germany: { mobile: 11, landline: 11, tollfree: 11 },
    france: { mobile: 10, landline: 10, tollfree: 10 },
    italy: { mobile: 10, landline: 10, tollfree: 10 },
    spain: { mobile: 9, landline: 9, tollfree: 9 },
    netherlands: { mobile: 10, landline: 10, tollfree: 10 },
    sweden: { mobile: 10, landline: 10, tollfree: 10 },
    norway: { mobile: 8, landline: 8, tollfree: 8 },
    denmark: { mobile: 8, landline: 8, tollfree: 8 },
    india: { mobile: 10, landline: 10, tollfree: 11 },
    japan: { mobile: 11, landline: 10, tollfree: 10 },
    china: { mobile: 11, landline: 11, tollfree: 11 },
  };

  const countryLengths = lengths[country] || { mobile: 10, landline: 10, tollfree: 10 };
  const type = numberType === 'tollfree' ? 'tollfree' : numberType === 'mobile' ? 'mobile' : 'landline';
  return countryLengths[type];
};

const generateRandomNumber = (length) => {
  const min = Math.pow(10, length - 1);
  const max = Math.pow(10, length) - 1;
  return String(randomInt(min, max));
};

const generateNumber = (country, numberType, format, specificAreaCode = 'random') => {
  const data = countryData[country];
  let areaCode, areaName, number, type;
  const totalLength = getTotalNumberLength(country, numberType);

  if (numberType === 'tollfree' && data.tollFree) {
    let selectedArea;
    if (specificAreaCode !== 'random') {
      const found = data.tollFree.find(ac => ac.code === specificAreaCode);
      selectedArea = found || data.tollFree[randomInt(0, data.tollFree.length - 1)];
    } else {
      selectedArea = data.tollFree[randomInt(0, data.tollFree.length - 1)];
    }
    areaCode = selectedArea.code;
    areaName = selectedArea.location;
    const numLength = totalLength - areaCode.length;
    number = generateRandomNumber(numLength);
    type = 'tollfree';
  } else if (numberType === 'mobile' && data.mobile) {
    let selectedArea;
    if (specificAreaCode !== 'random' && Array.isArray(data.mobile)) {
      const found = data.mobile.find(ac => ac.code === specificAreaCode);
      selectedArea = found || data.mobile[randomInt(0, data.mobile.length - 1)];
    } else if (Array.isArray(data.mobile)) {
      selectedArea = data.mobile[randomInt(0, data.mobile.length - 1)];
    } else {
      selectedArea = data.mobile[randomInt(0, data.mobile.length - 1)];
    }
    areaCode = selectedArea.code;
    areaName = selectedArea.location;
    const numLength = totalLength - areaCode.length;
    number = generateRandomNumber(numLength);
    type = 'mobile';
  } else if (data.areaCodes) {
    let selectedArea;
    if (specificAreaCode !== 'random') {
      const found = data.areaCodes.find(ac => ac.code === specificAreaCode);
      selectedArea = found || data.areaCodes[randomInt(0, data.areaCodes.length - 1)];
    } else {
      selectedArea = data.areaCodes[randomInt(0, data.areaCodes.length - 1)];
    }
    areaCode = selectedArea.code;
    areaName = selectedArea.location;
    const numLength = totalLength - areaCode.length;
    number = generateRandomNumber(numLength);
    type = numberType === 'mobile' ? 'mobile' : 'landline';
  } else {
    // For countries without specific area codes
    areaCode = '';
    areaName = 'N/A';
    number = generateRandomNumber(totalLength);
    type = numberType;
  }

  return {
    number: formatNumber(data.code, areaCode, number, format, country),
    areaCode: areaCode,
    areaName: areaName,
    type,
  };
};

export const getAreaCodesForCountry = (country, numberType) => {
  const data = countryData[country];
  if (!data) return [];

  if (numberType === 'tollfree' && data.tollFree) {
    return data.tollFree;
  } else if (numberType === 'mobile' && data.mobile) {
    // Check if mobile is array of objects or simple array
    if (Array.isArray(data.mobile) && typeof data.mobile[0] === 'object') {
      return data.mobile;
    }
    return []; // Simple array doesn't have locations
  } else if (data.areaCodes) {
    return data.areaCodes;
  }

  return [];
};

export const generatePhoneNumbers = (country, numberType, format, count, areaCode = 'random') => {
  const results = [];
  for (let i = 0; i < count; i++) {
    results.push(generateNumber(country, numberType, format, areaCode));
  }
  return results;
};
